=== AitorCalderonLo/Dam1/Aitor/Lenguaje de marcas/XML/ejer25/B/B/xsd.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="alumnos" type="tipoAlumnos" />

  <xs:complexType name="tipoAlumnos">
    <xs:sequence>
      <xs:element name="alumno" type="tipoAlumno" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoAlumno">
    <xs:sequence>
      <xs:element name="dni" type="xs:string" />
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="direccion" type="tipoDireccion" />
      <xs:choice>
        <xs:element name="telefono" type="xs:string" minOccurs="0" />
        <xs:element name="movil" type="xs:string" minOccurs="0" maxOccurs="3" />
      </xs:choice>
      <xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoDireccion">
    <xs:sequence>
      <xs:element name="calle" type="xs:string" />
      <xs:element name="numero" type="xs:string" />
      <xs:element name="ciudad" type="xs:string" />
      <xs:element name="provincia" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== AitorCalderonLo/Dam1/Aitor/Lenguaje de marcas/XML/ejer25/D/ej25D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
    <alumno dni="78921365c" repetidor="true" fechaNacimiento="1999-01-01">
        <nombre>Iraide Etxeberria</nombre>
        <direccion>
            <calle>plaza</calle>
            <numero>5</numero>
            <ciudad codPostal="48003">Bilbao</ciudad>
            <provincia>Bizkaia</provincia>
        </direccion>
        <telefono>944000000</telefono>
        <minusvalia grado="10%" />
    </alumno>
    <alumno dni="30258963G" fechaNacimiento="2001-02-10">
        <nombre>Joseba Mikel Zarraga</nombre>
        <direccion>
            <calle>avenida</calle>
            <numero>75</numero>
            <ciudad codPostal="48013">Artea</ciudad>
            <provincia>Bizkaia</provincia>
        </direccion>
        <movil>645652321</movil>
        <movil>645612321</movil>
        <movil>645653321</movil>
    </alumno>
</alumnos>
